# EFS CSI Driver는 AWS EKS Add-on을 통해 설치됩니다.
# 수동으로 설치하지 마세요.
---
# EFS StorageClass 정의
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0c8ce5c0e0d2b9601  # 실제 EFS ID로 변경 필요
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
---
# EFS Access Point 생성 (선택사항)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: sns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi 